code --install-extension christian-kohler.npm-intellisense
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension GitHub.github-vscode-theme
code --install-extension GregorBiswanger.json2ts
code --install-extension hashicorp.terraform
code --install-extension jdinhlife.gruvbox
code --install-extension liviuschera.noctis
code --install-extension mechatroner.rainbow-csv
code --install-extension mikestead.dotenv
code --install-extension mohsen1.prettify-json
code --install-extension mrmlnc.vscode-duplicate
code --install-extension ms-vscode.atom-keybindings
code --install-extension oderwat.indent-rainbow
code --install-extension rbbit.typescript-hero
code --install-extension sinedied.vscode-windows-xp-theme
code --install-extension wassimdev.windows-nt-vscode-theme
code --install-extension wayou.vscode-todo-highlight
