code --install-extension aaron-bond.better-comments
code --install-extension akamud.vscode-theme-onedark
code --install-extension akamud.vscode-theme-onelight
code --install-extension chriseckenrode.vscode-chester-atom
code --install-extension christian-kohler.npm-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension dbaeumer.vscode-eslint
code --install-extension GitHub.github-vscode-theme
code --install-extension jdinhlife.gruvbox
code --install-extension jolaleye.horizon-theme-vscode
code --install-extension liviuschera.noctis
code --install-extension Luxcium.pop-n-lock-theme-vscode
code --install-extension mechatroner.rainbow-csv
code --install-extension mikestead.dotenv
code --install-extension mohsen1.prettify-json
code --install-extension mrmlnc.vscode-duplicate
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode.atom-keybindings
code --install-extension Nimda.deepdark-material
code --install-extension oderwat.indent-rainbow
code --install-extension PKief.material-icon-theme
code --install-extension selfrefactor.niketa-dark-theme
code --install-extension wayou.vscode-todo-highlight
