code --install-extension christian-kohler.npm-intellisense
code --install-extension dbaeumer.vscode-eslint
code --install-extension GitHub.github-vscode-theme
code --install-extension jdinhlife.gruvbox
code --install-extension jolaleye.horizon-theme-vscode
code --install-extension liviuschera.noctis
code --install-extension mechatroner.rainbow-csv
code --install-extension mikestead.dotenv
code --install-extension mohsen1.prettify-json
code --install-extension mrmlnc.vscode-duplicate
code --install-extension ms-vscode.atom-keybindings
code --install-extension oderwat.indent-rainbow
code --install-extension wayou.vscode-todo-highlight
