
export ZSH="$HOME/.oh-my-zsh"

plugins=(git)

source $HOME/.aliases
source $HOME/.zshenv
source $ZSH/oh-my-zsh.sh

export NVM_DIR="$HOME/.nvm"

[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

# Set Spaceship ZSH as a prompt
autoload -U promptinit; promptinit
prompt spaceship

if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init --path)"
fi

export PATH="$HOME/.poetry/bin:$PATH"
