
export ZSH="$HOME/.oh-my-zsh"

plugins=(git)

source $HOME/.aliases
source $ZSH/oh-my-zsh.sh

export NVM_DIR="$HOME/.nvm"

[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

# Set Spaceship ZSH as a prompt
autoload -U promptinit; promptinit
prompt spaceship
